### ISSUE TITLE
UserAgent should be handled in the library

### ISSUE THREAD

**Issue by jney** [oystparis/oyst-php#34]
Librairie should handle the way the UserAgent is sent. It should be done by the constructor, or event better, be a global static variable.

The format should be the following:

`Oyst${CMS_PLATFORM}/${OYST_VERSION} (${CMS_PLATFORM} ${CMS_VERSION}, ${LANGUAGE_NAME} ${LANGUAGE_VERSION})`

where:
- `CMS_PLATFORM` is the current cms engine, ie: Prestashop, Magento, etc.
- `CMS_VERSION` is the current version of the `CMS_PLATFORM`
- `OYST_VERSION` is the current developed version
- `LANGUAGE_NAME` is the current language in which the plateform is developed
- `LANGUAGE_VERSION` is the current version of the language

ie:

`OystPrestashop/1.0.1 (Prestashop 1.6.1.4, php 5.3.2)`

see the incomplete format: https://github.com/OystParis/oyst-prestashop/blob/e76b7c2f9ef86cd29bcb81ec87919986d1c0b782/classes/OystSDK.php#L98

**Comment by mehdichaouch** [comment]
Duplicate task #33.
What about Magento data : https://github.com/oystparis/oyst-freepay-magento/blob/dbcdb8aeecba75a77503446fa5c339d42587ca6c/app/code/community/Oyst/Oyst/Model/Api.php#L334

And WooCommerce?

One more thing, an API version should be nice also:
```OystPrestashop/1.0.1 (Prestashop 1.6.1.4, php 5.3.2, sdk 1.2.0)```
