### ISSUE TITLE
champ limité freeshipping

### ISSUE THREAD

**Issue by quentinjunior** [oystparis/oyst-php#48]
Le free shipping est limité à 10 millions. 
L'erreur n'est pas explicite côté Magento

![image 1](https://user-images.githubusercontent.com/27730079/28717350-b980e474-73a1-11e7-91d5-08147968f3b1.png)

**Comment by mehdichaouch** [comment]
@quentinjunior please check with backend is this limit is logic.

**Comment by quentinjunior** [comment]
ca marche
